info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples

---
spring:
  profiles: default
configuration:  
  projectName: configclient
server:  
  port: 8888
message:  
  greeting: Hello from the configuration
  greeting1: Hello212121212
---
spring:
  profiles: default2
configuration:  
  projectName: configclient
---
